/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg.jpa.with.hibernate.assign;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
